server:
  port: 8091
  servlet:
    session:
      timeout: 18000
      #timeout: 1296000s #1个月
      cookie:
        name: SESSION
  tomcat:
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60
spring:
  datasource:
    name: master
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.190.133.146:3306/freeride_db
    username: root
    password: liliu
  redis:
    host: 118.190.133.146
    password: liliu
    port: 6379
    database: 1
    timeout: 3000
    jedis:
      pool:
        min-idle: 100
        max-idle: 300
        max-active: 800
    lettuce:
      pool:
        min-idle: 100
        max-idle: 300
        max-active: 800
myPugin:
  jmx:
    rmi:
      hostname: 118.190.133.146
      port: 1234
  uploaderPath:
    rootPath: /home
    locationPath: /uploaderPath/img
  session:
    myDomainName: boya1.cn
  projectName: freerideProject
  projectDomainUrl: http://ccsd.boya1.cn
  com.nieyue.shiro:
    anon:
      locations: / , /*.txt  , /swagger-resources/** , /swagger-ui.html , /webjars/** , /v2/** , /home/** , /resources/** ,/uploaderPath/**